server:
  port: 8769
spring:
  application:
    name: service-zuul
  zipkin:
    # base-url: http://localhost:9411/
    locator:
      discovery:
        enabled: true #自动发现
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /v1
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-feign
    api-b:
      path: /api-b/**
      serviceId: service-ribbon
    api-hi:
      path: /api-hi/**
      serviceId: service-hi
