spring:
  profiles:
    active: service-hi2
---
spring:
  profiles: service-hi1
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411/
    locator:
      discovery:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763

---
spring:
  profiles: service-hi2
  application:
    name: service-hi
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764



