server:
  port: 8769
spring:
  application:
    name: config-server
  #  profiles:
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liushuzheng/config-server
          search-paths:
          username: xiegutimo@aliyun.com
          password: xxx
        default-label: master
